/* tslint:disable */
// This file is generated
// Do not edit this file
import * as webhook from "./webhook/index";
export * as webhook from "./webhook/index";
import * as comment from "./comment/index";
export * as comment from "./comment/index";

export type Channels = {
  "webhook": webhook.Webhook;
  "comment": comment.Comment;
}
