/* tslint:disable */
// This file is generated
// Do not edit this file
import * as widget from "./widget/index";
export * as widget from "./widget/index";

export type Actions = {
  "widget": widget.Widget;
}
