/* tslint:disable */
// This file is generated
// Do not edit this file
import * as facebookAction from "./facebookAction/index";
export * as facebookAction from "./facebookAction/index";
import * as instaAction from "./instaAction/index";
export * as instaAction from "./instaAction/index";
import * as linkedInAction from "./linkedInAction/index";
export * as linkedInAction from "./linkedInAction/index";

export type Actions = {
  "facebookAction": facebookAction.FacebookAction;
  "instaAction": instaAction.InstaAction;
  "linkedInAction": linkedInAction.LinkedInAction;
}
