/* tslint:disable */
// This file is generated
// Do not edit this file
import * as facebook from "./facebook/index";
export * as facebook from "./facebook/index";

export type Actions = {
  "facebook": facebook.Facebook;
}
