/* tslint:disable */
// This file is generated
// Do not edit this file

import { Messages } from './messages/index'
export * from './messages/index'

export type Comment = {
  messages: Messages
  message: { "tags": { "id": { "title": "Message ID", "description": "Message ID from Stripe" } } }
  conversation: { "tags": { "taskId": { "title": "Task ID", "description": "Task ID from Stripe" } }, "creation": { "enabled": false, "requiredTags": [] } }
}